### ISSUE TITLE
WAF: Import issues

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/terraform-provider-opentelekomcloud#1655]
# Description of the enhancement
Current implementation of import in different WAF rules resources seems to be broken: `policy_id` should be part of the imported ID, but `ImportStatePassthroughContext` is used.

- [x] PP rule (#1658)
- [ ] web tamper rule (#1664)
- [ ] white/black IP rule (#1664)
- [ ] false alarm masking rule (#1664)
