### ISSUE TITLE
[Throttling] Use client from ctx

### ISSUE THREAD

**Issue by lego963** [opentelekomcloud/terraform-provider-opentelekomcloud#1848]
**resources**

- [x] - opentelekomcloud_compute_keypair_v2 #1857
- [x] - opentelekomcloud_kms_key_v1 #1866
- [x] - opentelekomcloud_vpc_eip_v1 #1849
- [x] - opentelekomcloud_networking_floatingip_associate_v2 #1853
- [x] - opentelekomcloud_networking_secgroup_v2
- [x] - opentelekomcloud_networking_secgroup_rule_v2
- [ ] - opentelekomcloud_obs_bucket
- [ ] - opentelekomcloud_obs_bucket_policy
- [x] - opentelekomcloud_vpc_v1
- [x] - opentelekomcloud_vpc_peering_connection_v2 #1853
- [x] - opentelekomcloud_vpc_route_v2 #1853
- [x] - opentelekomcloud_vpc_subnet_v1
- [x] - opentelekomcloud_cce_cluster_v3
- [x] - opentelekomcloud_cce_node_v3
- [x] - opentelekomcloud_ces_alarmrule #1847
- [x] - opentelekomcloud_lb_loadbalancer_v2 #1852
- [x] - opentelekomcloud_lb_listener_v2 #1852
- [x] - opentelekomcloud_lb_pool_v2 #1852
- [x] - opentelekomcloud_lb_monitor_v2 #1852
- [x] - opentelekomcloud_lb_whitelist_v2 #1852
- [x] - opentelekomcloud_lb_member_v2 #1852
- [x] - opentelekomcloud_lb_listener_v2 #1852
- [x] - opentelekomcloud_rds_instance_v3 #1873 
- [x] - opentelekomcloud_blockstorage_volume_v2 #1871
- [x] - opentelekomcloud_networking_port_v2 #1853
- [x] - opentelekomcloud_compute_instance_v2 #1857
- [x] - opentelekomcloud_dns_zone_v2 #1865
- [x] - opentelekomcloud_dns_recordset_v2 #1865
- [x] - opentelekomcloud_sfs_turbo_share_v1 #1870
- [x] - opentelekomcloud_identity_group_v3 #1880 
- [x] - opentelekomcloud_identity_group_membership_v3 #1880 
- [x] - opentelekomcloud_identity_role_assignment_v3 #1880 

_Originally posted by @Nemental in https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1840#issuecomment-1198994567_

**Comment by anton-sidelnikov** [comment]
All throttling issues should be fixed in v1.32.1
