### ISSUE TITLE
[Tags] tags support missing for several resources

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/terraform-provider-opentelekomcloud#532]
**Provider version:** 1.23.2

Following resources require a prioritized tag functionality support:

- [x] `opentelekomcloud_as_group_v1` (#877)
- [x] `opentelekomcloud_kms_key_v1` (#884)
- [x] `opentelekomcloud_lb_loadbalancer_v2` (#890)
- [x] `opentelekomcloud_sfs_file_system_v2` (#867)
- [x] `opentelekomcloud_vpc_eip_v1` (#830)
- [x] `opentelekomcloud_lb_listener_v2` (#895)
