### ISSUE TITLE
Unify usage of tags in resources

### ISSUE THREAD

**Issue by lego963** [opentelekomcloud/terraform-provider-opentelekomcloud#918]
- [x] `resource/opentelekomcloud_ecs_instance_v1` (#919)
- [x] `resource/opentelekomcloud_compute_instance_v2` (#927)
- [x] `resource/opentelekomcloud_rds_instance_v3` (#1085)
